# Generated by Django 4.0.5 on 2022-06-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JsonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('jsondata', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
