# Generated by Django 4.0.5 on 2022-06-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsondata',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
