# Generated by Django 4.0.5 on 2022-06-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_command_hostname_logdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInterfaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(null=True)),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.hostname')),
            ],
        ),
    ]
