# Generated by Django 4.0.5 on 2022-06-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_getinterfaces'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JsonData',
        ),
        migrations.RemoveField(
            model_name='logdata',
            name='command',
        ),
        migrations.RemoveField(
            model_name='logdata',
            name='hostname',
        ),
        migrations.DeleteModel(
            name='Command',
        ),
        migrations.DeleteModel(
            name='LogData',
        ),
    ]
